[package]
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
description = "Tokio based implementation of the RPC used in the Xi editor"
homepage = "https://github.com/little-dude/xi-rpc-tokio"
keywords = [
    "xi",
    "rpc",
    "json-rpc",
]
license-file = "LICENSE-MIT"
name = "xi-rpc-tokio"
readme = "README.md"
repository = "https://github.com/little-dude/xi-rpc-tokio"
version = "0.1.0"

[dependencies]
bytes = "0.4.5"
futures = "0.1.16"
log = "0.3.8"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
tokio-tls = "0.1.3"

[dependencies.clippy]
optional = true
version = "0.0.162"
